sonar.projectKey=vocab-app
sonar.projectName=vocab-app
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.inclusions=src/**/*.{js,jsx,ts,tsx}
sonar.exclusions=dist/**,node_modules/**,coverage/**,public/**
sonar.cpd.exclusions=src/data/**
