apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocab-app
  namespace: vocab
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: vocab-app
  template:
    metadata:
      labels:
        app: vocab-app
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: vocab-app
          image: harbor.watasoftware.com/vocab-app/vocab-app:stable
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              ephemeral-storage: 128Mi
              memory: 128Mi
            limits:
              cpu: 300m
              ephemeral-storage: 256Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: vocab-app
  namespace: vocab
spec:
  selector:
    app: vocab-app
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      protocol: TCP
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vocab-app
  namespace: vocab
spec:
  ingressClassName: traefik
  rules:
    - host: vocab.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vocab-app
                port:
                  number: 5173
